# Generated by Django 4.0.4 on 2023-04-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
