# Generated by Django 4.0.4 on 2023-04-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ticket_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='paystack_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
