# Generated by Django 4.0.4 on 2023-04-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ticket_paystack_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='paid',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
