# Generated by Django 4.0.4 on 2023-04-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ticket_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
